apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: worker
  labels:
    deployment: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: worker
  template:
    metadata:
      labels:
        pod: worker
    spec:
      containers:
        - name: worker
          image: urandu/face-detection-api:latest
          command: ["celery", "worker", "--app=api.celery_app", "--concurrency=2", "--hostname=worker@%h", "--loglevel=INFO"]
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: db_name

            - name: DATABASE_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: db_host

            - name: CELERY_BROKER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: host

            - name: CELERY_RESULT_BACKEND
              value: redis://redis-service:6379

            - name: REDIS_HOST
              value: redis-service
