apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
        tier: backend
    spec:
      containers:
        - name: minio
          image: "minio/minio"
          command: ["server", "/data"]
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: access_key

            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: secret_key

          ports:
            - containerPort: 9000
          volumeMounts:
            - name: minio-volume-mount
              mountPath: /data

      volumes:
        - name: minio-volume-mount
          persistentVolumeClaim:
            claimName: minio-pvc