kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: minio-pv