apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
data:
  user: dXNlcg==
  password: d2Vha19wYXNzd29yZA==
  host: ZGphbmdv


RABBITMQ_DEFAULT_USER=user
RABBITMQ_DEFAULT_PASS=weak_password
CELERY_BROKER=amqp://user:weak_password@broker:5672