apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    pod: rabbitmq
  ports:
  - name: port-1
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: port-2
    protocol: TCP
    port: 15672
    targetPort: 15672
  - name: port-3
    protocol: TCP
    port: 5671
    targetPort: 5671
  type: NodePort
